var countries = {
ABW: {fillKey: "defaultFill", name: "Aruba",},
AFG: {fillKey: "defaultFill", name: "Afghanistan",},
AGO: {fillKey: "defaultFill", name: "Angola",},
AIA: {fillKey: "defaultFill", name: "Anguilla",},
ALA: {fillKey: "defaultFill", name: "Åland Islands",},
ALB: {fillKey: "defaultFill", name: "Albania",},
AND: {fillKey: "defaultFill", name: "Andorra",},
ARE: {fillKey: "defaultFill", name: "United Arab Emirates",},
ARG: {fillKey: "defaultFill", name: "Argentina",},
ARM: {fillKey: "defaultFill", name: "Armenia",},
ASM: {fillKey: "defaultFill", name: "American Samoa",},
ATA: {fillKey: "defaultFill", name: "Antarctica",},
ATF: {fillKey: "defaultFill", name: "French Southern Territories",},
ATG: {fillKey: "defaultFill", name: "Antigua and Barbuda",},
AUS: {fillKey: "defaultFill", name: "Australia",},
AUT: {fillKey: "defaultFill", name: "Austria",},
AZE: {fillKey: "defaultFill", name: "Azerbaijan",},
BDI: {fillKey: "defaultFill", name: "Burundi",},
BEL: {fillKey: "defaultFill", name: "Belgium",},
BEN: {fillKey: "defaultFill", name: "Benin",},
BES: {fillKey: "defaultFill", name: "Bonaire",},
BFA: {fillKey: "defaultFill", name: "Burkina Faso",},
BGD: {fillKey: "defaultFill", name: "Bangladesh",},
BGR: {fillKey: "defaultFill", name: "Bulgaria",},
BHR: {fillKey: "defaultFill", name: "Bahrain",},
BHS: {fillKey: "defaultFill", name: "Bahamas",},
BIH: {fillKey: "defaultFill", name: "Bosnia and Herzegovina",},
BLM: {fillKey: "defaultFill", name: "Saint Barthélemy",},
BLR: {fillKey: "defaultFill", name: "Belarus",},
BLZ: {fillKey: "defaultFill", name: "Belize",},
BMU: {fillKey: "defaultFill", name: "Bermuda",},
BOL: {fillKey: "defaultFill", name: "Bolivia",},
BRA: {fillKey: "defaultFill", name: "Brazil",},
BRB: {fillKey: "defaultFill", name: "Barbados",},
BRN: {fillKey: "defaultFill", name: "Brunei Darussalam",},
BTN: {fillKey: "defaultFill", name: "Bhutan",},
BVT: {fillKey: "defaultFill", name: "Bouvet Island",},
BWA: {fillKey: "defaultFill", name: "Botswana",},
CAF: {fillKey: "defaultFill", name: "Central African Republic",},
CAN: {fillKey: "defaultFill", name: "Canada",},
CCK: {fillKey: "defaultFill", name: "Cocos (Keeling) Islands",},
CHE: {fillKey: "defaultFill", name: "Switzerland",},
CHL: {fillKey: "defaultFill", name: "Chile",},
CHN: {fillKey: "defaultFill", name: "China",},
CIV: {fillKey: "defaultFill", name: "Côte d'Ivoire",},
CMR: {fillKey: "defaultFill", name: "Cameroon",},
COD: {fillKey: "defaultFill", name: "Congo",},
COG: {fillKey: "defaultFill", name: "Congo",},
COK: {fillKey: "defaultFill", name: "Cook Islands",},
COL: {fillKey: "defaultFill", name: "Colombia",},
COM: {fillKey: "defaultFill", name: "Comoros",},
CPV: {fillKey: "defaultFill", name: "Cabo Verde",},
CRI: {fillKey: "defaultFill", name: "Costa Rica",},
CUB: {fillKey: "defaultFill", name: "Cuba",},
CUW: {fillKey: "defaultFill", name: "Curaçao",},
CXR: {fillKey: "defaultFill", name: "Christmas Island",},
CYM: {fillKey: "defaultFill", name: "Cayman Islands",},
CYP: {fillKey: "defaultFill", name: "Cyprus",},
CZE: {fillKey: "defaultFill", name: "Czech Republic",},
DEU: {fillKey: "defaultFill", name: "Germany",},
DJI: {fillKey: "defaultFill", name: "Djibouti",},
DMA: {fillKey: "defaultFill", name: "Dominica",},
DNK: {fillKey: "defaultFill", name: "Denmark",},
DOM: {fillKey: "defaultFill", name: "Dominican Republic",},
DZA: {fillKey: "defaultFill", name: "Algeria",},
ECU: {fillKey: "defaultFill", name: "Ecuador",},
EGY: {fillKey: "defaultFill", name: "Egypt",},
ERI: {fillKey: "defaultFill", name: "Eritrea",},
ESH: {fillKey: "defaultFill", name: "Western Sahara",},
ESP: {fillKey: "defaultFill", name: "Spain",},
EST: {fillKey: "defaultFill", name: "Estonia",},
ETH: {fillKey: "defaultFill", name: "Ethiopia",},
FIN: {fillKey: "defaultFill", name: "Finland",},
FJI: {fillKey: "defaultFill", name: "Fiji",},
FLK: {fillKey: "defaultFill", name: "Falkland Islands (Malvinas)",},
FRA: {fillKey: "defaultFill", name: "France",},
FRO: {fillKey: "defaultFill", name: "Faroe Islands",},
FSM: {fillKey: "defaultFill", name: "Micronesia",},
GAB: {fillKey: "defaultFill", name: "Gabon",},
GBR: {fillKey: "defaultFill", name: "United Kingdom",},
GEO: {fillKey: "defaultFill", name: "Georgia",},
GGY: {fillKey: "defaultFill", name: "Guernsey",},
GHA: {fillKey: "defaultFill", name: "Ghana",},
GIB: {fillKey: "defaultFill", name: "Gibraltar",},
GIN: {fillKey: "defaultFill", name: "Guinea",},
GLP: {fillKey: "defaultFill", name: "Guadeloupe",},
GMB: {fillKey: "defaultFill", name: "Gambia",},
GNB: {fillKey: "defaultFill", name: "Guinea-Bissau",},
GNQ: {fillKey: "defaultFill", name: "Equatorial Guinea",},
GRC: {fillKey: "defaultFill", name: "Greece",},
GRD: {fillKey: "defaultFill", name: "Grenada",},
GRL: {fillKey: "defaultFill", name: "Greenland",},
GTM: {fillKey: "defaultFill", name: "Guatemala",},
GUF: {fillKey: "defaultFill", name: "French Guiana",},
GUM: {fillKey: "defaultFill", name: "Guam",},
GUY: {fillKey: "defaultFill", name: "Guyana",},
HKG: {fillKey: "defaultFill", name: "Hong Kong",},
HMD: {fillKey: "defaultFill", name: "Heard Island and McDonald Islands",},
HND: {fillKey: "defaultFill", name: "Honduras",},
HRV: {fillKey: "defaultFill", name: "Croatia",},
HTI: {fillKey: "defaultFill", name: "Haiti",},
HUN: {fillKey: "defaultFill", name: "Hungary",},
IDN: {fillKey: "defaultFill", name: "Indonesia",},
IMN: {fillKey: "defaultFill", name: "Isle of Man",},
IND: {fillKey: "defaultFill", name: "India",},
IOT: {fillKey: "defaultFill", name: "British Indian Ocean Territory",},
IRL: {fillKey: "defaultFill", name: "Ireland",},
IRN: {fillKey: "defaultFill", name: "Iran",},
IRQ: {fillKey: "defaultFill", name: "Iraq",},
ISL: {fillKey: "defaultFill", name: "Iceland",},
ISR: {fillKey: "defaultFill", name: "Israel",},
ITA: {fillKey: "defaultFill", name: "Italy",},
JAM: {fillKey: "defaultFill", name: "Jamaica",},
JEY: {fillKey: "defaultFill", name: "Jersey",},
JOR: {fillKey: "defaultFill", name: "Jordan",},
JPN: {fillKey: "defaultFill", name: "Japan",},
KAZ: {fillKey: "defaultFill", name: "Kazakhstan",},
KEN: {fillKey: "defaultFill", name: "Kenya",},
KGZ: {fillKey: "defaultFill", name: "Kyrgyzstan",},
KHM: {fillKey: "defaultFill", name: "Cambodia",},
KIR: {fillKey: "defaultFill", name: "Kiribati",},
KNA: {fillKey: "defaultFill", name: "Saint Kitts and Nevis",},
KOR: {fillKey: "defaultFill", name: "Korea, Republic of",},
KWT: {fillKey: "defaultFill", name: "Kuwait",},
LAO: {fillKey: "defaultFill", name: "Laos",},
LBN: {fillKey: "defaultFill", name: "Lebanon",},
LBR: {fillKey: "defaultFill", name: "Liberia",},
LBY: {fillKey: "defaultFill", name: "Libya",},
LCA: {fillKey: "defaultFill", name: "Saint Lucia",},
LIE: {fillKey: "defaultFill", name: "Liechtenstein",},
LKA: {fillKey: "defaultFill", name: "Sri Lanka",},
LSO: {fillKey: "defaultFill", name: "Lesotho",},
LTU: {fillKey: "defaultFill", name: "Lithuania",},
LUX: {fillKey: "defaultFill", name: "Luxembourg",},
LVA: {fillKey: "defaultFill", name: "Latvia",},
MAC: {fillKey: "defaultFill", name: "Macao",},
MAF: {fillKey: "defaultFill", name: "Saint Martin",},
MAR: {fillKey: "defaultFill", name: "Morocco",},
MCO: {fillKey: "defaultFill", name: "Monaco",},
MDA: {fillKey: "defaultFill", name: "Moldova",},
MDG: {fillKey: "defaultFill", name: "Madagascar",},
MDV: {fillKey: "defaultFill", name: "Maldives",},
MEX: {fillKey: "defaultFill", name: "Mexico",},
MHL: {fillKey: "defaultFill", name: "Marshall Islands",},
MKD: {fillKey: "defaultFill", name: "Macedonia",},
MLI: {fillKey: "defaultFill", name: "Mali",},
MLT: {fillKey: "defaultFill", name: "Malta",},
MMR: {fillKey: "defaultFill", name: "Myanmar",},
MNE: {fillKey: "defaultFill", name: "Montenegro",},
MNG: {fillKey: "defaultFill", name: "Mongolia",},
MNP: {fillKey: "defaultFill", name: "Northern Mariana Islands",},
MOZ: {fillKey: "defaultFill", name: "Mozambique",},
MRT: {fillKey: "defaultFill", name: "Mauritania",},
MSR: {fillKey: "defaultFill", name: "Montserrat",},
MTQ: {fillKey: "defaultFill", name: "Martinique",},
MUS: {fillKey: "defaultFill", name: "Mauritius",},
MWI: {fillKey: "defaultFill", name: "Malawi",},
MYS: {fillKey: "defaultFill", name: "Malaysia",},
MYT: {fillKey: "defaultFill", name: "Mayotte",},
NAM: {fillKey: "defaultFill", name: "Namibia",},
NCL: {fillKey: "defaultFill", name: "New Caledonia",},
NER: {fillKey: "defaultFill", name: "Niger",},
NFK: {fillKey: "defaultFill", name: "Norfolk Island",},
NGA: {fillKey: "defaultFill", name: "Nigeria",},
NIC: {fillKey: "defaultFill", name: "Nicaragua",},
NIU: {fillKey: "defaultFill", name: "Niue",},
NLD: {fillKey: "defaultFill", name: "Netherlands",},
NOR: {fillKey: "defaultFill", name: "Norway",},
NPL: {fillKey: "defaultFill", name: "Nepal",},
NRU: {fillKey: "defaultFill", name: "Nauru",},
NZL: {fillKey: "defaultFill", name: "New Zealand",},
OMN: {fillKey: "defaultFill", name: "Oman",},
PAK: {fillKey: "defaultFill", name: "Pakistan",},
PAN: {fillKey: "defaultFill", name: "Panama",},
PCN: {fillKey: "defaultFill", name: "Pitcairn",},
PER: {fillKey: "defaultFill", name: "Peru",},
PHL: {fillKey: "defaultFill", name: "Philippines",},
PLW: {fillKey: "defaultFill", name: "Palau",},
PNG: {fillKey: "defaultFill", name: "Papua New Guinea",},
POL: {fillKey: "defaultFill", name: "Poland",},
PRI: {fillKey: "defaultFill", name: "Puerto Rico",},
PRK: {fillKey: "defaultFill", name: "Korea",},
PRT: {fillKey: "defaultFill", name: "Portugal",},
PRY: {fillKey: "defaultFill", name: "Paraguay",},
PSE: {fillKey: "defaultFill", name: "Palestine",},
PYF: {fillKey: "defaultFill", name: "French Polynesia",},
QAT: {fillKey: "defaultFill", name: "Qatar",},
REU: {fillKey: "defaultFill", name: "Réunion",},
ROU: {fillKey: "defaultFill", name: "Romania",},
RUS: {fillKey: "defaultFill", name: "Russian Federation",},
RWA: {fillKey: "defaultFill", name: "Rwanda",},
SAU: {fillKey: "defaultFill", name: "Saudi Arabia",},
SDN: {fillKey: "defaultFill", name: "Sudan",},
SEN: {fillKey: "defaultFill", name: "Senegal",},
SGP: {fillKey: "defaultFill", name: "Singapore",},
SGS: {fillKey: "defaultFill", name: "South Georgia and the South Sandwich Islands",},
SHN: {fillKey: "defaultFill", name: "Saint Helena, Ascension and Tristan da Cunha",},
SJM: {fillKey: "defaultFill", name: "Svalbard and Jan Mayen",},
SLB: {fillKey: "defaultFill", name: "Solomon Islands",},
SLE: {fillKey: "defaultFill", name: "Sierra Leone",},
SLV: {fillKey: "defaultFill", name: "El Salvador",},
SMR: {fillKey: "defaultFill", name: "San Marino",},
SOM: {fillKey: "defaultFill", name: "Somalia",},
SPM: {fillKey: "defaultFill", name: "Saint Pierre and Miquelon",},
SRB: {fillKey: "defaultFill", name: "Serbia",},
SSD: {fillKey: "defaultFill", name: "South Sudan",},
STP: {fillKey: "defaultFill", name: "Sao Tome and Principe",},
SUR: {fillKey: "defaultFill", name: "Suriname",},
SVK: {fillKey: "defaultFill", name: "Slovakia",},
SVN: {fillKey: "defaultFill", name: "Slovenia",},
SWE: {fillKey: "defaultFill", name: "Sweden",},
SWZ: {fillKey: "defaultFill", name: "Swaziland",},
SXM: {fillKey: "defaultFill", name: "Sint Maarten (Dutch part)",},
SYC: {fillKey: "defaultFill", name: "Seychelles",},
SYR: {fillKey: "defaultFill", name: "Syrian Arab Republic",},
TCA: {fillKey: "defaultFill", name: "Turks and Caicos Islands",},
TCD: {fillKey: "defaultFill", name: "Chad",},
TGO: {fillKey: "defaultFill", name: "Togo",},
THA: {fillKey: "defaultFill", name: "Thailand",},
TJK: {fillKey: "defaultFill", name: "Tajikistan",},
TKL: {fillKey: "defaultFill", name: "Tokelau",},
TKM: {fillKey: "defaultFill", name: "Turkmenistan",},
TLS: {fillKey: "defaultFill", name: "Timor-Leste",},
TON: {fillKey: "defaultFill", name: "Tonga",},
TTO: {fillKey: "defaultFill", name: "Trinidad and Tobago",},
TUN: {fillKey: "defaultFill", name: "Tunisia",},
TUR: {fillKey: "defaultFill", name: "Turkey",},
TUV: {fillKey: "defaultFill", name: "Tuvalu",},
TWN: {fillKey: "defaultFill", name: "Taiwan",},
TZA: {fillKey: "defaultFill", name: "Tanzania",},
UGA: {fillKey: "defaultFill", name: "Uganda",},
UKR: {fillKey: "defaultFill", name: "Ukraine",},
UMI: {fillKey: "defaultFill", name: "United States Minor Outlying Islands",},
URY: {fillKey: "defaultFill", name: "Uruguay",},
USA: {fillKey: "defaultFill", name: "United States"},
UZB: {fillKey: "defaultFill", name: "Uzbekistan",},
VAT: {fillKey: "defaultFill", name: "Holy See (Vatican City State)",},
VCT: {fillKey: "defaultFill", name: "Saint Vincent and the Grenadines",},
VEN: {fillKey: "defaultFill", name: "Venezuela",},
VGB: {fillKey: "defaultFill", name: "British Virgin Islands",},
VIR: {fillKey: "defaultFill", name: "US Virgin Islands",},
VNM: {fillKey: "defaultFill", name: "Viet Nam",},
VUT: {fillKey: "defaultFill", name: "Vanuatu",},
WLF: {fillKey: "defaultFill", name: "Wallis and Futuna",},
WSM: {fillKey: "defaultFill", name: "Samoa",},
YEM: {fillKey: "defaultFill", name: "Yemen",},
ZAF: {fillKey: "defaultFill", name: "South Africa",},
ZMB: {fillKey: "defaultFill", name: "Zambia",},
ZWE: {fillKey: "defaultFill", name: "Zimbabwe",},
// "-99": {name: "Somaliland"}
}

var personalCountries = {
ABW: {fillKey: "defaultFill", name: "Aruba",},
AFG: {fillKey: "defaultFill", name: "Afghanistan",},
AGO: {fillKey: "defaultFill", name: "Angola",},
AIA: {fillKey: "defaultFill", name: "Anguilla",},
ALA: {fillKey: "defaultFill", name: "Åland Islands",},
ALB: {fillKey: "defaultFill", name: "Albania",},
AND: {fillKey: "defaultFill", name: "Andorra",},
ARE: {fillKey: "defaultFill", name: "United Arab Emirates",},
ARG: {fillKey: "defaultFill", name: "Argentina",},
ARM: {fillKey: "defaultFill", name: "Armenia",},
ASM: {fillKey: "defaultFill", name: "American Samoa",},
ATA: {fillKey: "defaultFill", name: "Antarctica",},
ATF: {fillKey: "defaultFill", name: "French Southern Territories",},
ATG: {fillKey: "defaultFill", name: "Antigua and Barbuda",},
AUS: {fillKey: "defaultFill", name: "Australia",},
AUT: {fillKey: "defaultFill", name: "Austria",},
AZE: {fillKey: "defaultFill", name: "Azerbaijan",},
BDI: {fillKey: "defaultFill", name: "Burundi",},
BEL: {fillKey: "defaultFill", name: "Belgium",},
BEN: {fillKey: "defaultFill", name: "Benin",},
BES: {fillKey: "defaultFill", name: "Bonaire",},
BFA: {fillKey: "defaultFill", name: "Burkina Faso",},
BGD: {fillKey: "defaultFill", name: "Bangladesh",},
BGR: {fillKey: "defaultFill", name: "Bulgaria",},
BHR: {fillKey: "defaultFill", name: "Bahrain",},
BHS: {fillKey: "defaultFill", name: "Bahamas",},
BIH: {fillKey: "defaultFill", name: "Bosnia and Herzegovina",},
BLM: {fillKey: "defaultFill", name: "Saint Barthélemy",},
BLR: {fillKey: "defaultFill", name: "Belarus",},
BLZ: {fillKey: "defaultFill", name: "Belize",},
BMU: {fillKey: "defaultFill", name: "Bermuda",},
BOL: {fillKey: "defaultFill", name: "Bolivia",},
BRA: {fillKey: "defaultFill", name: "Brazil",},
BRB: {fillKey: "defaultFill", name: "Barbados",},
BRN: {fillKey: "defaultFill", name: "Brunei Darussalam",},
BTN: {fillKey: "defaultFill", name: "Bhutan",},
BVT: {fillKey: "defaultFill", name: "Bouvet Island",},
BWA: {fillKey: "defaultFill", name: "Botswana",},
CAF: {fillKey: "defaultFill", name: "Central African Republic",},
CAN: {fillKey: "defaultFill", name: "Canada",},
CCK: {fillKey: "defaultFill", name: "Cocos (Keeling) Islands",},
CHE: {fillKey: "defaultFill", name: "Switzerland",},
CHL: {fillKey: "defaultFill", name: "Chile",},
CHN: {fillKey: "defaultFill", name: "China",},
CIV: {fillKey: "defaultFill", name: "Côte d'Ivoire",},
CMR: {fillKey: "defaultFill", name: "Cameroon",},
COD: {fillKey: "defaultFill", name: "Congo",},
COG: {fillKey: "defaultFill", name: "Congo",},
COK: {fillKey: "defaultFill", name: "Cook Islands",},
COL: {fillKey: "defaultFill", name: "Colombia",},
COM: {fillKey: "defaultFill", name: "Comoros",},
CPV: {fillKey: "defaultFill", name: "Cabo Verde",},
CRI: {fillKey: "defaultFill", name: "Costa Rica",},
CUB: {fillKey: "defaultFill", name: "Cuba",},
CUW: {fillKey: "defaultFill", name: "Curaçao",},
CXR: {fillKey: "defaultFill", name: "Christmas Island",},
CYM: {fillKey: "defaultFill", name: "Cayman Islands",},
CYP: {fillKey: "defaultFill", name: "Cyprus",},
CZE: {fillKey: "defaultFill", name: "Czech Republic",},
DEU: {fillKey: "defaultFill", name: "Germany",},
DJI: {fillKey: "defaultFill", name: "Djibouti",},
DMA: {fillKey: "defaultFill", name: "Dominica",},
DNK: {fillKey: "defaultFill", name: "Denmark",},
DOM: {fillKey: "defaultFill", name: "Dominican Republic",},
DZA: {fillKey: "defaultFill", name: "Algeria",},
ECU: {fillKey: "defaultFill", name: "Ecuador",},
EGY: {fillKey: "defaultFill", name: "Egypt",},
ERI: {fillKey: "defaultFill", name: "Eritrea",},
ESH: {fillKey: "defaultFill", name: "Western Sahara",},
ESP: {fillKey: "defaultFill", name: "Spain",},
EST: {fillKey: "defaultFill", name: "Estonia",},
ETH: {fillKey: "defaultFill", name: "Ethiopia",},
FIN: {fillKey: "defaultFill", name: "Finland",},
FJI: {fillKey: "defaultFill", name: "Fiji",},
FLK: {fillKey: "defaultFill", name: "Falkland Islands (Malvinas)",},
FRA: {fillKey: "defaultFill", name: "France",},
FRO: {fillKey: "defaultFill", name: "Faroe Islands",},
FSM: {fillKey: "defaultFill", name: "Micronesia",},
GAB: {fillKey: "defaultFill", name: "Gabon",},
GBR: {fillKey: "defaultFill", name: "United Kingdom",},
GEO: {fillKey: "defaultFill", name: "Georgia",},
GGY: {fillKey: "defaultFill", name: "Guernsey",},
GHA: {fillKey: "defaultFill", name: "Ghana",},
GIB: {fillKey: "defaultFill", name: "Gibraltar",},
GIN: {fillKey: "defaultFill", name: "Guinea",},
GLP: {fillKey: "defaultFill", name: "Guadeloupe",},
GMB: {fillKey: "defaultFill", name: "Gambia",},
GNB: {fillKey: "defaultFill", name: "Guinea-Bissau",},
GNQ: {fillKey: "defaultFill", name: "Equatorial Guinea",},
GRC: {fillKey: "defaultFill", name: "Greece",},
GRD: {fillKey: "defaultFill", name: "Grenada",},
GRL: {fillKey: "defaultFill", name: "Greenland",},
GTM: {fillKey: "defaultFill", name: "Guatemala",},
GUF: {fillKey: "defaultFill", name: "French Guiana",},
GUM: {fillKey: "defaultFill", name: "Guam",},
GUY: {fillKey: "defaultFill", name: "Guyana",},
HKG: {fillKey: "defaultFill", name: "Hong Kong",},
HMD: {fillKey: "defaultFill", name: "Heard Island and McDonald Islands",},
HND: {fillKey: "defaultFill", name: "Honduras",},
HRV: {fillKey: "defaultFill", name: "Croatia",},
HTI: {fillKey: "defaultFill", name: "Haiti",},
HUN: {fillKey: "defaultFill", name: "Hungary",},
IDN: {fillKey: "defaultFill", name: "Indonesia",},
IMN: {fillKey: "defaultFill", name: "Isle of Man",},
IND: {fillKey: "defaultFill", name: "India",},
IOT: {fillKey: "defaultFill", name: "British Indian Ocean Territory",},
IRL: {fillKey: "defaultFill", name: "Ireland",},
IRN: {fillKey: "defaultFill", name: "Iran",},
IRQ: {fillKey: "defaultFill", name: "Iraq",},
ISL: {fillKey: "defaultFill", name: "Iceland",},
ISR: {fillKey: "defaultFill", name: "Israel",},
ITA: {fillKey: "defaultFill", name: "Italy",},
JAM: {fillKey: "defaultFill", name: "Jamaica",},
JEY: {fillKey: "defaultFill", name: "Jersey",},
JOR: {fillKey: "defaultFill", name: "Jordan",},
JPN: {fillKey: "defaultFill", name: "Japan",},
KAZ: {fillKey: "defaultFill", name: "Kazakhstan",},
KEN: {fillKey: "defaultFill", name: "Kenya",},
KGZ: {fillKey: "defaultFill", name: "Kyrgyzstan",},
KHM: {fillKey: "defaultFill", name: "Cambodia",},
KIR: {fillKey: "defaultFill", name: "Kiribati",},
KNA: {fillKey: "defaultFill", name: "Saint Kitts and Nevis",},
KOR: {fillKey: "defaultFill", name: "Korea, Republic of",},
KWT: {fillKey: "defaultFill", name: "Kuwait",},
LAO: {fillKey: "defaultFill", name: "Laos",},
LBN: {fillKey: "defaultFill", name: "Lebanon",},
LBR: {fillKey: "defaultFill", name: "Liberia",},
LBY: {fillKey: "defaultFill", name: "Libya",},
LCA: {fillKey: "defaultFill", name: "Saint Lucia",},
LIE: {fillKey: "defaultFill", name: "Liechtenstein",},
LKA: {fillKey: "defaultFill", name: "Sri Lanka",},
LSO: {fillKey: "defaultFill", name: "Lesotho",},
LTU: {fillKey: "defaultFill", name: "Lithuania",},
LUX: {fillKey: "defaultFill", name: "Luxembourg",},
LVA: {fillKey: "defaultFill", name: "Latvia",},
MAC: {fillKey: "defaultFill", name: "Macao",},
MAF: {fillKey: "defaultFill", name: "Saint Martin",},
MAR: {fillKey: "defaultFill", name: "Morocco",},
MCO: {fillKey: "defaultFill", name: "Monaco",},
MDA: {fillKey: "defaultFill", name: "Moldova",},
MDG: {fillKey: "defaultFill", name: "Madagascar",},
MDV: {fillKey: "defaultFill", name: "Maldives",},
MEX: {fillKey: "defaultFill", name: "Mexico",},
MHL: {fillKey: "defaultFill", name: "Marshall Islands",},
MKD: {fillKey: "defaultFill", name: "Macedonia",},
MLI: {fillKey: "defaultFill", name: "Mali",},
MLT: {fillKey: "defaultFill", name: "Malta",},
MMR: {fillKey: "defaultFill", name: "Myanmar",},
MNE: {fillKey: "defaultFill", name: "Montenegro",},
MNG: {fillKey: "defaultFill", name: "Mongolia",},
MNP: {fillKey: "defaultFill", name: "Northern Mariana Islands",},
MOZ: {fillKey: "defaultFill", name: "Mozambique",},
MRT: {fillKey: "defaultFill", name: "Mauritania",},
MSR: {fillKey: "defaultFill", name: "Montserrat",},
MTQ: {fillKey: "defaultFill", name: "Martinique",},
MUS: {fillKey: "defaultFill", name: "Mauritius",},
MWI: {fillKey: "defaultFill", name: "Malawi",},
MYS: {fillKey: "defaultFill", name: "Malaysia",},
MYT: {fillKey: "defaultFill", name: "Mayotte",},
NAM: {fillKey: "defaultFill", name: "Namibia",},
NCL: {fillKey: "defaultFill", name: "New Caledonia",},
NER: {fillKey: "defaultFill", name: "Niger",},
NFK: {fillKey: "defaultFill", name: "Norfolk Island",},
NGA: {fillKey: "defaultFill", name: "Nigeria",},
NIC: {fillKey: "defaultFill", name: "Nicaragua",},
NIU: {fillKey: "defaultFill", name: "Niue",},
NLD: {fillKey: "defaultFill", name: "Netherlands",},
NOR: {fillKey: "defaultFill", name: "Norway",},
NPL: {fillKey: "defaultFill", name: "Nepal",},
NRU: {fillKey: "defaultFill", name: "Nauru",},
NZL: {fillKey: "defaultFill", name: "New Zealand",},
OMN: {fillKey: "defaultFill", name: "Oman",},
PAK: {fillKey: "defaultFill", name: "Pakistan",},
PAN: {fillKey: "defaultFill", name: "Panama",},
PCN: {fillKey: "defaultFill", name: "Pitcairn",},
PER: {fillKey: "defaultFill", name: "Peru",},
PHL: {fillKey: "defaultFill", name: "Philippines",},
PLW: {fillKey: "defaultFill", name: "Palau",},
PNG: {fillKey: "defaultFill", name: "Papua New Guinea",},
POL: {fillKey: "defaultFill", name: "Poland",},
PRI: {fillKey: "defaultFill", name: "Puerto Rico",},
PRK: {fillKey: "defaultFill", name: "Korea",},
PRT: {fillKey: "defaultFill", name: "Portugal",},
PRY: {fillKey: "defaultFill", name: "Paraguay",},
PSE: {fillKey: "defaultFill", name: "Palestine",},
PYF: {fillKey: "defaultFill", name: "French Polynesia",},
QAT: {fillKey: "defaultFill", name: "Qatar",},
REU: {fillKey: "defaultFill", name: "Réunion",},
ROU: {fillKey: "defaultFill", name: "Romania",},
RUS: {fillKey: "defaultFill", name: "Russian Federation",},
RWA: {fillKey: "defaultFill", name: "Rwanda",},
SAU: {fillKey: "defaultFill", name: "Saudi Arabia",},
SDN: {fillKey: "defaultFill", name: "Sudan",},
SEN: {fillKey: "defaultFill", name: "Senegal",},
SGP: {fillKey: "defaultFill", name: "Singapore",},
SGS: {fillKey: "defaultFill", name: "South Georgia and the South Sandwich Islands",},
SHN: {fillKey: "defaultFill", name: "Saint Helena, Ascension and Tristan da Cunha",},
SJM: {fillKey: "defaultFill", name: "Svalbard and Jan Mayen",},
SLB: {fillKey: "defaultFill", name: "Solomon Islands",},
SLE: {fillKey: "defaultFill", name: "Sierra Leone",},
SLV: {fillKey: "defaultFill", name: "El Salvador",},
SMR: {fillKey: "defaultFill", name: "San Marino",},
SOM: {fillKey: "defaultFill", name: "Somalia",},
SPM: {fillKey: "defaultFill", name: "Saint Pierre and Miquelon",},
SRB: {fillKey: "defaultFill", name: "Serbia",},
SSD: {fillKey: "defaultFill", name: "South Sudan",},
STP: {fillKey: "defaultFill", name: "Sao Tome and Principe",},
SUR: {fillKey: "defaultFill", name: "Suriname",},
SVK: {fillKey: "defaultFill", name: "Slovakia",},
SVN: {fillKey: "defaultFill", name: "Slovenia",},
SWE: {fillKey: "defaultFill", name: "Sweden",},
SWZ: {fillKey: "defaultFill", name: "Swaziland",},
SXM: {fillKey: "defaultFill", name: "Sint Maarten (Dutch part)",},
SYC: {fillKey: "defaultFill", name: "Seychelles",},
SYR: {fillKey: "defaultFill", name: "Syrian Arab Republic",},
TCA: {fillKey: "defaultFill", name: "Turks and Caicos Islands",},
TCD: {fillKey: "defaultFill", name: "Chad",},
TGO: {fillKey: "defaultFill", name: "Togo",},
THA: {fillKey: "defaultFill", name: "Thailand",},
TJK: {fillKey: "defaultFill", name: "Tajikistan",},
TKL: {fillKey: "defaultFill", name: "Tokelau",},
TKM: {fillKey: "defaultFill", name: "Turkmenistan",},
TLS: {fillKey: "defaultFill", name: "Timor-Leste",},
TON: {fillKey: "defaultFill", name: "Tonga",},
TTO: {fillKey: "defaultFill", name: "Trinidad and Tobago",},
TUN: {fillKey: "defaultFill", name: "Tunisia",},
TUR: {fillKey: "defaultFill", name: "Turkey",},
TUV: {fillKey: "defaultFill", name: "Tuvalu",},
TWN: {fillKey: "defaultFill", name: "Taiwan",},
TZA: {fillKey: "defaultFill", name: "Tanzania",},
UGA: {fillKey: "defaultFill", name: "Uganda",},
UKR: {fillKey: "defaultFill", name: "Ukraine",},
UMI: {fillKey: "defaultFill", name: "United States Minor Outlying Islands",},
URY: {fillKey: "defaultFill", name: "Uruguay",},
USA: {fillKey: "defaultFill", name: "United States"},
UZB: {fillKey: "defaultFill", name: "Uzbekistan",},
VAT: {fillKey: "defaultFill", name: "Holy See (Vatican City State)",},
VCT: {fillKey: "defaultFill", name: "Saint Vincent and the Grenadines",},
VEN: {fillKey: "defaultFill", name: "Venezuela",},
VGB: {fillKey: "defaultFill", name: "British Virgin Islands",},
VIR: {fillKey: "defaultFill", name: "US Virgin Islands",},
VNM: {fillKey: "defaultFill", name: "Viet Nam",},
VUT: {fillKey: "defaultFill", name: "Vanuatu",},
WLF: {fillKey: "defaultFill", name: "Wallis and Futuna",},
WSM: {fillKey: "defaultFill", name: "Samoa",},
YEM: {fillKey: "defaultFill", name: "Yemen",},
ZAF: {fillKey: "defaultFill", name: "South Africa",},
ZMB: {fillKey: "defaultFill", name: "Zambia",},
ZWE: {fillKey: "defaultFill", name: "Zimbabwe",},
// "-99": {name: "Somaliland"}
}

var mapElement = document.getElementById('map');
if (mapElement) {
  $.get('https://arcane-castle-8723.herokuapp.com/users').then(function (response) {
    var defaultData = {};
    response.body.forEach(function (user) {
      for (var country in countries) {
        if (countries.hasOwnProperty(country)) {
          defaultData[country] = defaultData[country] || countries[country]
          if (user.country === defaultData[country].name) {
            defaultData[country].value = defaultData[country].value + 1 || 1
            if (defaultData[country].value > 2 && defaultData[country].value < 6) {
              defaultData[country].fillKey = "medium"
            } else if (defaultData[country].value > 5) {
              defaultData[country].fillKey = "high"
            } else {
              defaultData[country].fillKey = "low"
            }
          }
        }
      }
    })
    var map = new Datamap({
      element: mapElement,
      projection: 'mercator',
      responsive: true,
      fills: {
        defaultFill: "#A39BA8",
        low: "#B8C5D6",
        medium: "#747b83",
        high: "#3c4045",
      },
      done: datamap => {
        datamap.svg.selectAll('.datamaps-subunit').on('click', function(geography, data) {
          console.log(geography, data);
          window.location.href = '/search?country=' + geography.properties.name.toLowerCase()
        });
      },
      data: defaultData,
      geographyConfig: {
        highlightBorderColor: '#7d7d7d',
        highlightBorderWidth: 1,
        popupTemplate: (geo, data) => {
            if (!data.value) {
              data.value = 0;
              var llama = "llamas"
            } else if (data.value == 1){
              var llama = "llama"
            } else {
              var llama = "llamas"
            }
            return ['<div class="hoverinfo"><strong>',
              geo.properties.name, "<br>", data.llamas,
                data.value, " ", llama,
                '</strong></div>'].join('');
        }
      }
    });
  $(window).on('resize', function() {
   map.resize();
  });
  })
}

var personalMapElement = document.getElementById('personalMap');
if (personalMapElement) {
  var id = $.cookie('user');
  var url = window.location.pathname.substring(1)
  $.post('https://arcane-castle-8723.herokuapp.com/user/world', {id, url}).then(function (data) {
    var defaultData = personalCountries;
    var fillIndex = {
      "1": "authorHasTraveledTo",
      "2": "authorHasLivedIn",
      "3": "authorWantsToGo",
      "4": "authorHasNotTraveled",
    }
    for (var key in data.body) {
      if (data.body.hasOwnProperty(key) && key !== "userId") {
        if (key !== "_id") {
          defaultData[key].fillKey = fillIndex[data.body[key]]
          defaultData[key].value = data.body[key]
        }
      }
    }
    var personalMap = new Datamap({
      element: personalMapElement,
      projection: 'mercator',
      responsive: true,
      fills: {
        defaultFill: "#A39BA8",
        authorHasNotTraveled: "#A39BA8",
        authorHasTraveledTo: "#4d65a2",
        authorHasLivedIn: "#23CE6B",
        authorWantsToGo: "#add49b"
      },
      done: datamap => {
        datamap.svg.selectAll('.datamaps-subunit').on('click', function(geography) {
          defaultData[geography.id].value = Number(defaultData[geography.id].value) + 1 || 1;
          if (defaultData[geography.id].value > 4) {
            defaultData[geography.id].value = 1;
          }
          $.post('https://arcane-castle-8723.herokuapp.com/user/update/world', {id: id, country: geography.id, value: defaultData[geography.id].value}).then(function (data) {
            defaultData[geography.id].fillKey = fillIndex[String((defaultData[geography.id].value))];
            personalMap.updateChoropleth(defaultData);
            personalMap.resize()
          })
        });
      },
      data: defaultData,
      geographyConfig: {
        highlightOnHover: false,
        highlightBorderColor: '#7d7d7d',
        highlightBorderWidth: 1,
        popupTemplate: (geo, data) => {
            return ['<div class="hoverinfo"><strong>',
              geo.properties.name, "<br>",
                '</strong></div>'].join('');
        }
      }
    });
    $(window).on('resize', function() {
      personalMap.resize();
    });
  })
}
